# Generated by Django 5.0.1 on 2025-09-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=200, verbose_name="密码")),
                ("create_time", models.DateField(null=True, verbose_name="创建时间")),
            ],
            options={
                "db_table": "t_user",
            },
        ),
    ]
