# Generated by Django 5.0.1 on 2025-09-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tuser",
            old_name="create_time",
            new_name="createtime",
        ),
    ]
